# Generated by Django 2.2.6 on 2019-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('core', '0003_pontoturistico_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
