# Generated by Django 2.2.6 on 2019-11-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191102_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='comentarios.Comentario'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.Review'),
        ),
    ]
